//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datn_qlch_be.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("datn_qlch_be.Core.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi xảy ra.
        /// </summary>
        internal static string VN_HaveAnErrorOccurred {
            get {
                return ResourceManager.GetString("VN_HaveAnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã món ăn đã tồn tại.
        /// </summary>
        internal static string VN_ValidateError_FoodCodeExitsed {
            get {
                return ResourceManager.GetString("VN_ValidateError_FoodCodeExitsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã món ăn không được phép để trống.
        /// </summary>
        internal static string VN_ValidateError_FoodCodeNotEmpty {
            get {
                return ResourceManager.GetString("VN_ValidateError_FoodCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sở thích bị trùng.
        /// </summary>
        internal static string VN_ValidateError_FoodFavoriteIsDuplicate {
            get {
                return ResourceManager.GetString("VN_ValidateError_FoodFavoriteIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên món ăn không được phép để trống.
        /// </summary>
        internal static string VN_ValidateError_FoodNameNotEmpty {
            get {
                return ResourceManager.GetString("VN_ValidateError_FoodNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán không được phép để trống.
        /// </summary>
        internal static string VN_ValidateError_FoodSellPriceNotEmpty {
            get {
                return ResourceManager.GetString("VN_ValidateError_FoodSellPriceNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuế không được phép để trống.
        /// </summary>
        internal static string VN_ValidateError_FoodTaxNotEmpty {
            get {
                return ResourceManager.GetString("VN_ValidateError_FoodTaxNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị không được phép để trống.
        /// </summary>
        internal static string VN_ValidateError_FoodUnitNameNotEmpty {
            get {
                return ResourceManager.GetString("VN_ValidateError_FoodUnitNameNotEmpty", resourceCulture);
            }
        }
    }
}
