//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datn_qlch_be.Core.Resources.vn {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmployeeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("datn_qlch_be.Core.Resources.vn.EmployeeResource", typeof(EmployeeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên không được để trống.
        /// </summary>
        internal static string EmployeeNameIsRequire {
            get {
                return ResourceManager.GetString("EmployeeNameIsRequire", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to Mật khẩu không đúng.
        /// </summary>
        internal static string PasswordInCorrect {
            get {
                return ResourceManager.GetString("PasswordInCorrect", resourceCulture);
            }
        }
        
        /// <summary>
=======
>>>>>>> a2420c4b2b22e57a2d91072034b6f0c119899d7b
        ///   Looks up a localized string similar to Mật khẩu không được để trống.
        /// </summary>
        internal static string PasswordIsRequire {
            get {
                return ResourceManager.GetString("PasswordIsRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã tồn tại.
        /// </summary>
        internal static string PhoneNumberIsExisted {
            get {
                return ResourceManager.GetString("PhoneNumberIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to Số điện thoại không tồn tại trong hệ thống.
        /// </summary>
        internal static string PhoneNumberIsNotExistInSystem {
            get {
                return ResourceManager.GetString("PhoneNumberIsNotExistInSystem", resourceCulture);
            }
        }
        
        /// <summary>
=======
>>>>>>> a2420c4b2b22e57a2d91072034b6f0c119899d7b
        ///   Looks up a localized string similar to Số điện thoại không được để trống.
        /// </summary>
        internal static string PhoneNumberIsRequire {
            get {
                return ResourceManager.GetString("PhoneNumberIsRequire", resourceCulture);
            }
        }
    }
}
